### ISSUE TITLE
行事曆

### ISSUE THREAD

**Issue by lulalala** [lulalala/ccsc#1]
預計 2 小時

各 group 定期更新接下來會有什麼活動。

前台有一頁 /schedules ，
該頁會出現每個 group 最新的一則內容
各 group 都是有個標題，然後再顯示內容
最後則是小字顯示更新日期

後台：
index 頁面列出過往所有 schedules ，依照 group 各自一群。
每個 schedules 可使用 created at 來命名作區別，點進去後可編輯。

新增時有一個 body 欄位，靠 ckeditor 貼上文章（通常從 word 貼上表格之類的東西）
也要指定跟哪個 group 有關（所以需要 group_id）

**Comment by lulalala** [comment]
前台：
1. 麻煩改成每個都是整個row的，因為文件會比較寬（會放表格），所以整頁寬才放的下。也許得不用panel才行。
2. 日期前面多寫個 “最後更新於 ”

後台：
1. 可以把 show 拿掉，因為通常用不到，目前也是沒有escaped的

前後台的修改的commit分開來～～
感謝～～

**Comment by chinlan** [comment]
![image](https://cloud.githubusercontent.com/assets/14109108/13959763/5c2a9d14-f090-11e5-8cdd-115ef69003ab.png)
關於前台更新日期的部分修正如圖（覺得放標頭的話寫「更新日期」會比較符合）
看看這樣覺得如何？
