### ISSUE TITLE
Fountain 作目錄頁

### ISSUE THREAD

**Issue by lulalala** [lulalala/ccsc#2]
預計 1050

Fountain 目前會自動產生目錄表，排序純粹依照 created_at
需求是能夠隨意讓編輯排序，並且加上分類（類似 http://ccsc.pixnet.net/blog/post/405301849）

所以先在 Fountain 加上一個 text 欄位來存 HTML。一個 model 的 function 產生一連串連結到 post 的 <a>，存到這個欄位。

一個 controller action ，讓管理者按一個按鈕即可呼叫這個 function ，產生最簡單的目錄表。

然後 fountain/show 就顯示這個目錄表。
fountain edit 有個 textarea 能夠修改這個目錄表。

**Comment by chinlan** [comment]
分支：fountain_catalogue

**Comment by lulalala** [comment]
Fixed by #3
