### ISSUE TITLE
文化福傳

### ISSUE THREAD

**Issue by lulalala** [lulalala/ccsc#4]
文化福傳是一個放相關文章的地方。文章各自獨立，沒有分期數。
範例文章請見：http://inthislife.pixnet.net/blog/post/320202664

- [x] 為 Post 添加能夠作 tagging 的功能，選個 tagging gem 先讓我評估一下。
- [x] 作個 CultureEntry 的 model，belongs to Post
- [x] 後台：Admin CultureEntries Controller 能新增與編輯 CultureEntry 的文章，並且加上 tag
- [x] 前台有 /culture_preaching 的 path 指向 CultureEntries Controller ，顯示所有以及個別文章。

預計 1400

**Comment by lulalala** [comment]
以後要修改 global 設定（如 ruby version 或是 config/ 下面的設定）先讓我評估下，這類修改也分開作 commit。

資料庫 migration / gem 安裝也是獨立作 commit，方便獨立修改。

**Comment by chinlan** [comment]
看範例文章看不太出來和原本Post的功用有什麼不同...
對於文化福傳這邊的功能敘述不太清楚，請問和心泉的結構的差異是？
CultureEntry 和Post是一對多關聯嗎？還是一對一呢？

**Comment by lulalala** [comment]
Post 是個泛用性的文章容器。文化福傳跟心泉都靠它儲存文章資料。

文化福傳不是像是雜誌一樣，有分期數。所以只會有一個列表頁。

CultureEntry belongs_to :post

**Comment by chinlan** [comment]
push到新分支culture_preaching了～

**Comment by lulalala** [comment]
* 學 http://www.ccsctw.org/ 在前台加上 nav menu 連到 culture_preaching 的 index （放在服務與生活下）
* #show 標籤跟「標籤」標誌放同一行
* 後台也有個 index 頁面，跟 nav menu ，並把 admin posts#index 裡面「新增文化福傳文章」連結移到 index 頁面

**Comment by lulalala** [comment]
- [ ] 把標籤改為「關鍵字」
- [ ] culture entry 增加一string欄位，叫做 category 作為分類用。目前有三個值，為 "詣" "小故事小道理" "論文" ，加入 seed 。
- [ ] 後台編輯預設為 "小故事小道理"
- [ ] culture_preaching#index 頁面設計如下：

![20160427_223216](https://cloud.githubusercontent.com/assets/366910/14855911/84422584-0cc8-11e6-83c1-d24632d3ab21.jpg)

### Index 

最大標題(居中)：文化福傳──反映基督信仰與中華文化

(居中) 詣
 文章1(齊左) 直接列出 標題 和 作者 名稱(不須 列 標題 作者 這兩個詞)
 文章2(齊左)

(居中) 小故事小道理 

 文章1(齊左) 直接列出 標題 和 作者 名稱(最上面不須 列 標題 作者 這兩個詞)
 文章2(齊左)

(大順序為  "詣" "小故事小道理" "論文"，該類別沒文章就不顯示標題)

### 標籤頁

文化福傳──反映基督信仰與中華文化

 <tag> 相關文章
 文章1(齊左) 直接列出 標題 和 作者 名稱
 文章2(齊左)

**Comment by chinlan** [comment]
已經push到culture_preaching分支，
tag那邊的路徑是用custom routes，因為會和action show的路徑打架，現在的做法是在show路徑加上限制id只能是數字。
`get '/culture_preaching', to: 'culture_entries#index', as: :culture_preaching 
 
 get '/culture_preaching/:id', to: 'culture_entries#show', as: :culture_preaching_post, constraints: {id: /\d+/ }
  
  get '/culture_preaching/:tag', to: 'culture_entries#tag', as: :culture_preaching_tag`

**Comment by lulalala** [comment]
![capturfiles_5](https://cloud.githubusercontent.com/assets/366910/15249659/4e2772be-1953-11e6-9276-ca94d7d00ad2.png)

每篇文章沒有分行

幫我再檢查一次後台，之前沒有連結到edit去，編輯的功能也許也有問題。CRUD幫我測過一遍。

每頁文章加入 disqus 功能

**Comment by chinlan** [comment]
編輯功能已修好，
文章加上換行和間距，
![image](https://cloud.githubusercontent.com/assets/14109108/15267397/d621c75a-19f3-11e6-8ecd-1cfffcd360de.png)

**Comment by lulalala** [comment]
okie 感謝。漫長的旅程辛苦了~~
